### ISSUE TITLE
displays nothing

### ISSUE THREAD

**Issue by synthview** [Tosche/Waterfall#1]
in Console 29/04/17 15:41:07,867 Glyphs[510]: -[NSNull set]: unrecognized selector sent to instance 0x7fff79148240

mac os 10.9.5

**Comment by Tosche** [comment]
Fixed.

**Comment by synthview** [comment]
Cool now I see the waterfall :) however, line hight isn’t correct, lines overlap :/

**Comment by Tosche** [comment]
Could you tell me your font's vertical metrics setting?

**Comment by synthview** [comment]
maybe it’s because I’m on 2000 units per Em
![schermata 2017-04-29 alle 17 58 51](https://cloud.githubusercontent.com/assets/1451689/25556876/9097510c-2d05-11e7-9433-ce90a51f0dae.png)

**Comment by Tosche** [comment]
I see, I'll work on it.

**Comment by synthview** [comment]
you’re the best  :1st_place_medal:

**Comment by Tosche** [comment]
Fixed. Now it supports any UPM.
